name: "Dev branch build, test, deploy - CI"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: "cache pip installed deps"
        uses: actions/cache@v4
        with: 
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{ hashfiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.9, 3.10, 3.11]
    needs: build
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Check python version ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Retrieve cache"
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashfiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Recreate virtual env (without installing again --> use cache)"
        run: |
          python --version
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: "Run tests"
        run: |
          source venv/bin/activate
          pytest --junitxml=test-results.xml
      - name: "Upload test results"
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}.xml
          path: test-results.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "deploy using opentofu"
        run: echo "Hello World :)"
        
