name: "Dev branch build, test, deploy - CI"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: "Save virtual env"
        uses: actions/upload-artifact@v4
        with: 
          name: venv
          path: venv


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Retrieve virtual env"
        uses: actions/download-artifact@v4
        with: 
          name: venv
          path: venv
      - name: "Activate virtual environement"
        run: source venv/bin/activate
      - name: "Run pytest"
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "deploy using opentofu"
        run: echo "Hello World :)"
        
